# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cyberchef
  namespace: tools
spec:
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        strategy: RollingUpdate
        initContainers:
          copy:
            image:
              repository: ghcr.io/gchq/cyberchef
              tag: 10.23.0@sha256:9f9205cfc20368bd9a4152f7708a9e7626525d8f4eadb1a25e5079708c5c4304
            command: ["cp", "-a", "/usr/share/nginx/html/.", "/html"]
        containers:
          app:
            image:
              repository: ghcr.io/nginx/nginx-unprivileged
              tag: stable-alpine
              pullPolicy: Always
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: { drop: [ALL] }
        pod:
          labels:
            policy.gabe565.com/ingress-envoy-public: "true"
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }

    persistence:
      html:
        type: emptyDir
        advancedMounts:
          main:
            copy:
              - path: /html
            app:
              - path: /usr/share/nginx/html
                readOnly: true
      tmp:
        type: emptyDir

    service:
      main:
        ports:
          http:
            port: 8080

    route:
      main:
        parentRefs:
          - namespace: envoy-gateway-system
            name: envoy-public
        hostnames:
          - ${cyberchef_host}
        rules:
          - backendRefs:
              - identifier: main
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  set:
                    - name: X-Robots-Tag
                      value: none
