apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: headscale
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-minimal-trixie@sha256:0fae0cb527912426a889ec0b21b9733e5b76fdc6ad8909914a6e8a6c8ba4f64b
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: headscale
      owner: headscale
  storage:
    storageClass: local-path
    size: 8Gi
  resources:
    requests:
      memory: 50Mi
      cpu: 20m
  smartShutdownTimeout: 1
  stopDelay: 300
  postgresql:
    parameters:
      archive_timeout: "0"
  primaryLease:
    leaseDurationSeconds: 60
    renewDeadlineSeconds: 40
    retryPeriodSeconds: 10
