apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: kgateway-public
  namespace: envoy-gateway-system
spec:
  endpoints:
    - fqdn:
        hostname: public.kgateway-system.svc.cluster.local
        port: 443
  tls:
    insecureSkipVerify: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fallback-to-kgateway
  namespace: envoy-gateway-system
spec:
  parentRefs:
    - name: envoy-public
      sectionName: https
  rules:
    - filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Proto
                value: https
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: kgateway-public
          port: 443
