apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: public
  namespace: envoy-gateway-system
spec:
  mergeBackends: {}
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        initContainers:
          - name: geoip
            image: ghcr.io/maxmind/geoipupdate:v8.0.0@sha256:51e70dd6f16cd3e4d845ac02d09940b10772a75b9d741427d235a78570923c1d
            restartPolicy: Always
            env:
              - name: GEOIPUPDATE_HOST
                value: http://geoip-updates.geoip
              - name: GEOIPUPDATE_FREQUENCY
                value: "8"
              - name: GEOIPUPDATE_PRESERVE_FILE_TIMES
                value: "1"
              - name: GEOIPUPDATE_EDITION_IDS
                value: GeoLite2-Country
              - name: GEOIPUPDATE_ACCOUNT_ID
                value: "1"
              - name: GEOIPUPDATE_LICENSE_KEY
                value: stub
            securityContext:
              readOnlyRootFilesystem: true
            startupProbe:
              exec:
                command: [ls, /usr/share/GeoIP/GeoLite2-Country.mmdb]
              periodSeconds: 5
              failureThreshold: 30
            volumeMounts:
              - name: geoip
                mountPath: /usr/share/GeoIP
              - name: geoip-tmp
                mountPath: /tmp
        pod:
          labels:
            policy.gabe565.com/egress-envoy-public: "true"
            policy.gabe565.com/egress-geoip: "true"
            policy.gabe565.com/egress-namespace: "true"
          volumes:
            - name: geoip
              emptyDir: {}
            - name: geoip-tmp
              emptyDir:
                medium: Memory
        container:
          volumeMounts:
            - name: geoip
              mountPath: /usr/share/GeoIP
              readOnly: true
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  hostAliases:
                    - ip: 10.43.0.20
                      hostnames:
                        - ${oidc_host}
      envoyService:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.220
        externalTrafficPolicy: Local
        patch:
          type: StrategicMerge
          value:
            spec:
              clusterIP: 10.43.0.20
  geoIP:
    provider:
      type: MaxMind
      maxMind:
        countryDbSource:
          local:
            path: /usr/share/GeoIP/GeoLite2-Country.mmdb
  telemetry:
    accessLog:
      settings:
        - format:
            type: JSON
            json:
              # Request
              method: "%REQ(:METHOD)%"
              path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
              protocol: "%PROTOCOL%"
              authority: "%REQ(:AUTHORITY)%"
              user_agent: "%REQ(USER-AGENT)%"
              client_ip: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
              route_name: "%ROUTE_NAME%"
              # Response
              response_code: "%RESPONSE_CODE%"
              response_flags: "%RESPONSE_FLAGS%"
              response_code_details: "%RESPONSE_CODE_DETAILS%"
              connection_termination_details: "%CONNECTION_TERMINATION_DETAILS%"
              upstream_transport_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
              bytes_received: "%BYTES_RECEIVED%"
              bytes_sent: "%BYTES_SENT%"
              duration: "%DURATION%"
              upstream_host: "%UPSTREAM_HOST%"
              upstream_cluster: "%UPSTREAM_CLUSTER%"
          sinks:
            - type: OpenTelemetry
              openTelemetry:
                backendRefs:
                  - group: gateway.envoyproxy.io
                    kind: Backend
                    name: alloy-otlp
                resourceAttributes:
                  service.name: envoy-gateway
                  k8s.cluster.name: gabernetes
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: alloy-otlp
  namespace: envoy-gateway-system
spec:
  appProtocols:
    - gateway.envoyproxy.io/h2c
  endpoints:
    - fqdn:
        hostname: alloy.prometheus.svc.cluster.local
        port: 4317
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: public
  namespace: envoy-gateway-system
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    namespace: envoy-gateway-system
    name: public
---
## Deployed from my private repo to keep certificate names private.
# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: public
#   namespace: envoy-gateway-system
# spec:
#   gatewayClassName: public
#   listeners:
#     - name: http
#       port: 80
#       protocol: HTTP
#       allowedRoutes:
#         namespaces:
#           from: Same
#     - name: https
#       port: 443
#       protocol: HTTPS
#       tls:
#         mode: Terminate
#         certificateRefs: []
#       allowedRoutes:
#         namespaces:
#           from: All
