apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: home-assistant
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.11-minimal-bookworm@sha256:c50c1966e00b485533dae5d410837d0f5026265cbbee0e18ad7346702e78384f
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: home-assistant
      owner: home-assistant
  storage:
    storageClass: local-path
    size: 8Gi
  resources:
    requests:
      memory: 400Mi
      cpu: 10m
  smartShutdownTimeout: 1
  stopDelay: 300
  postgresql:
    parameters:
      archive_timeout: "0"
      checkpoint_timeout: 30min
  primaryLease:
    leaseDurationSeconds: 60
    renewDeadlineSeconds: 40
    retryPeriodSeconds: 10
