apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: home-assistant
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-minimal-trixie@sha256:4467d4cf7e502fbc29800b75d755ede477a765b25a506a58a0842a57a4bf42c9
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: home-assistant
      owner: home-assistant
  storage:
    storageClass: local-path
    size: 8Gi
  resources:
    requests:
      memory: 400Mi
      cpu: 10m
  smartShutdownTimeout: 1
  stopDelay: 300
  postgresql:
    parameters:
      archive_timeout: "0"
      checkpoint_timeout: 30min
  primaryLease:
    leaseDurationSeconds: 60
    renewDeadlineSeconds: 40
    retryPeriodSeconds: 10
