apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: watch-your-lan
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.11-minimal-trixie@sha256:cfc42005357630d2c0bfca095c93a6abe44884486acb0de2e5e511a087b7eb15
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: lan
      owner: lan
  storage:
    storageClass: local-path
    size: 8Gi
  resources:
    requests:
      memory: 10Mi
      cpu: 10m
  smartShutdownTimeout: 1
  stopDelay: 300
  postgresql:
    parameters:
      archive_timeout: "0"
  primaryLease:
    leaseDurationSeconds: 60
    renewDeadlineSeconds: 40
    retryPeriodSeconds: 10
