# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: vikunja
spec:
  chart:
    spec:
      chart: app-template
      version: 5.0.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  interval: 1h
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: valkey-defaults
  values:
    controllers:
      valkey:
        containers:
          valkey:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.0.4-alpine@sha256:d1cc70645bbcef743615463a2fa4616e841407545e18f560aed0c49671a90147

    persistence:
      data:
        type: emptyDir

    secrets:
      valkey:
        stringData:
          valkey-password: ${valkey_password}
