apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: authentik
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-minimal-trixie@sha256:37ade18dbdddba430858c72725aceeec66f33fa5333e82ea1df4942f6c1c83a3
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "200"
      archive_timeout: "0"
      checkpoint_timeout: 30min
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  storage:
    storageClass: local-path
    size: 8Gi
  resources:
    requests:
      memory: 50Mi
      cpu: 20m
  smartShutdownTimeout: 1
  stopDelay: 300
  primaryLease:
    leaseDurationSeconds: 60
    renewDeadlineSeconds: 40
    retryPeriodSeconds: 10
