apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crds
  namespace: kgateway-system
spec:
  chart:
    spec:
      chart: kgateway-crds
      version: v2.3.0-main
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: kgateway-system
        name: kgateway
  interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
