# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.0.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: nightscout
spec:
  chart:
    spec:
      chart: app-template
      version: 5.0.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  interval: 1h
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: mongodb-defaults
  values:
    controllers:
      mongodb:
        containers:
          mongodb:
            image:
              repository: mongo
              tag: 8.3.4@sha256:0f887198e29c093fd2b36c3e2eb43c7b98e47c081d89fbd5bc212da0cd43ec58
            env:
              MONGO_INITDB_DATABASE: nightscout
              MONGODB_EXTRA_USERNAMES: nightscout

    persistence:
      data:
        storageClass: longhorn-ssd
        accessMode: ReadWriteOnce
        size: 8Gi
        retain: true

    secrets:
      mongodb:
        stringData:
          mongodb-root-password: ${mongodb_root_password}
          mongodb-passwords: ${mongodb_password}
