# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.0.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  chart:
    spec:
      chart: app-template
      version: 5.0.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controllers:
      home-assistant:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.7.4@sha256:fc3c0b5f7c2ff61a81b3c84dfcc405d3ff28bfc73caf68fb5c31818515f3554e
              pullPolicy: IfNotPresent
            env:
              TZ: America/Chicago
              DATABASE_URL:
                secretKeyRef:
                  name: postgresql-app
                  key: uri
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: { drop: [ALL] }
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: ipvlan
          labels:
            policy.gabe565.com/egress-mosquitto: "true"
            policy.gabe565.com/egress-namespace: "true"
            policy.gabe565.com/egress-nightscout: "true"
            policy.gabe565.com/egress-nodes: "true"
            policy.gabe565.com/egress-tronbyt: "true"
            policy.gabe565.com/egress-world-with-lan: "true"
            policy.gabe565.com/ingress-envoy-public: "true"
            policy.gabe565.com/ingress-world: "true"
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }

    persistence:
      config:
        suffix: config
        storageClass: longhorn-ssd
        accessMode: ReadWriteOnce
        size: 2Gi
        retain: true
      tmp:
        type: emptyDir
        medium: Memory

    service:
      home-assistant:
        controller: home-assistant
        primary: true
        ports:
          http:
            port: 8123

    route:
      app:
        parentRefs:
          - namespace: envoy-gateway-system
            name: public
        hostnames:
          - ${app_url}
        rules:
          - backendRefs:
              - identifier: home-assistant
