apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: cni-plugins-plan
  namespace: system-upgrade
spec:
  concurrency: 3
  nodeSelector: {}
  tolerations:
    - key: gabe565.com/gpu
      operator: Exists
      effect: NoSchedule
  upgrade:
    image: ghcr.io/home-operations/cni-plugins
  version: 1.9.1
