apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: shlink
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-minimal-bookworm@sha256:17697898a5150b9cb32061e3ac46776c7c912edf7b0775c6afd83ba098eaf734
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: shlink
      owner: shlink
  storage:
    storageClass: local-path
    size: 8Gi
  resources:
    requests:
      memory: 10Mi
      cpu: 10m
  smartShutdownTimeout: 1
  stopDelay: 300
  postgresql:
    parameters:
      archive_timeout: "0"
  primaryLease:
    leaseDurationSeconds: 60
    renewDeadlineSeconds: 40
    retryPeriodSeconds: 10
